spring.application.name=backend
spring.data.mongodb.uri=mongodb+srv://pamudithasenanayake_db_user:6z2N1JOVjnzOlFu7@cluster0.2pv8a2t.mongodb.net/lms?appName=Cluster0
google.client.id=${GOOGLE_CLIENT_ID:916544102316-85ocp1vglfhaer9ulob2bvbl9hdervd1.apps.googleusercontent.com}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

file.upload.dir=${FILE_UPLOAD_DIR:./uploads}
