spring.application.name=backend
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/lms}
google.client.id=${GOOGLE_CLIENT_ID:916544102316-85ocp1vglfhaer9ulob2bvbl9hdervd1.apps.googleusercontent.com}
